# -*- coding: utf-8 -*-
"""MLops data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CbQgFPxzjpscSLuTIAtjQ2klRkzWicH
"""

import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

df=pd.read_csv("/content/sample_data/flipkard.csv.w.csv")

df.head()

df.describe()

df.shape

df.tail()

df.describe()

df.color

df.hist(figsize=(20, 20))
plt.show()

df.boxplot(figsize=(20, 20),)
plt.show()

df.columns

sns.stripplot(y='product_score',data=df,jitter=True)

from sklearn.model_selection import train_test_split

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
X = df[numeric_cols].drop(columns=['product_score'])
y = df['product_score']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.02, random_state=42)

X_train.shape,X_test.shape,X.shape

y_train.shape,y_test.shape,y.shape

df.head()

from sklearn.naive_bayes import GaussianNB

naive_model = GaussianNB()

naive_model

naive_model.fit(X_train, y_train.astype(int))


naive_model.score(X_test, y_test.astype(int))*100

from sklearn.neighbors import KNeighborsClassifier

from sklearn.tree import DecisionTreeClassifier

from sklearn.svm import SVC

from sklearn.linear_model import LogisticRegression

knn_model =KNeighborsClassifier()

dtree = DecisionTreeClassifier()

svm_model = SVC()

lgmodel = LogisticRegression()

mlist = [knn_model,dtree,svm_model,lgmodel]

mlist

import time

for i in mlist:
  print(i)
  time.sleep(1)

import warnings
warnings.filterwarnings('ignore')

for i in mlist:
  i.fit(X_train, y_train.astype(int))
  score = i.score(X_test, y_test.astype(int))
  print(i, end='==')
  print(score)
  time.sleep(2)

